### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by sgillis**
Build multiple images with different tags

@dirkmoors

### CODE REVIEW

**Comment by dirkmoors** [comment]
@sgillis Could you split up the makefile functionality to an explicit "build" and a "publish" phase?

e.g.:
```
$ make build  # Creates the Dockerfile from the template, and builds the Docker image locally
$ make push  # Pushes the Dockerfile to the predefined registry
```

**Comment by dirkmoors** [comment]
Also, could you add documentation/comments to the makefile, and add a 'step by step' example to the README.rst?

**Comment by dirkmoors** [comment]
@sgillis Do we want to have a specific Django version preinstalled? Django is typically installed allong with the other requirements...

**Comment by sgillis** [comment]
@dirkmoors what do you think about these new changes?

**Pull request merged**
